### ISSUE TITLE
Inbound Webhook?

### ISSUE THREAD

**Issue by NickChristensen** [captn3m0/ifttt-webhook#6]
This is so great! Do you know of something that does the inverse of this? Like I could POST to a url, and it would trigger an IFTTT action?

**Comment by captn3m0** [comment]
Interesting. The best channels I can think of for that would be email. Other channels are periodically checked and are not real-time. But if you send a mail to trigger@ifttt.com, it triggers the response pretty fast.

There are many email as REST services around, use any one.

**Comment by NickChristensen** [comment]
Cool, thanks for the tip!
