### ISSUE TITLE
Maker channel versus a clone of this repo

### ISSUE THREAD

**Issue by codecowboy** [captn3m0/ifttt-webhook#9]
If I want to have a tweet event trigger another channel and include the contents of the tweet in the subsequent call to a webhook, do you know if I would be better off cloning this repo or if the Maker channel can support this functionality?

Apologies for posting here but IFTTT have been very slow at responding in the past.

My aim is to post to the NodeBB API and create a forum post including the tweet contents (plus any images). I'm just trying to ascertain whether I should write custom code for this or if it is achievable with IFTTT as the latter will probably be faster and cheaper to develop.

**Comment by captn3m0** [comment]
I haven't used the maker channel, but from what I know, it just fires off a webhook with the trigger data. However, if you want to perform slight modifications in the data (such as dropping and adding fields), I'm not sure if Maker channel supports that.

Another service that I liked was hookify.io, but its still in closed beta (I do have an account). That would probably allow zero code nodebb posting.

**Comment by codecowboy** [comment]
@captn3m0 thanks. An invite code for hookify would be lovely. Tweet it to @codecowboy if you are feeling generous ;)

**Comment by captn3m0** [comment]
I actually poked them on their support channel and asked for one before posting this comment.
